### ISSUE TITLE
Please consider updating the DCG link

### ISSUE THREAD

**Issue by triska** [klauscfhq/awesome-prolog#1]
Hi Klaus,

I am providing an updated Definite Clause Grammars (DCG) tutorial at:

https://www.metalevel.at/prolog/dcg

The text you currently link to is based on an outdated (old) version of my tutorial, which was copied without my permission.

If possible, please consider updating the link. Thank you!

**Comment by klauscfhq** [comment]
It will be updated right away. Thank you a lot for taking the time to point it out : )

**Comment by triska** [comment]
Thank you very much for this nice collection of links!
