### ISSUE TITLE
Please consider upgrading CLP(FD) to CLP(Z)

### ISSUE THREAD

**Issue by triska** [klauscfhq/awesome-prolog#3]
Hi Klaus,

I am the author of the CLP(FD) system of SWI-Prolog that is described in one of the tutorials you currently link to. Since last&nbsp;year, I have moved development to SICStus Prolog, and the new system is called CLP(**Z**). Users are strongly encouraged to migrate to&nbsp;CLP(Z)!

Therefore, to point to the more recent developments, please consider linking to one of the following texts instead:

https://github.com/triska/clpz

or

https://www.metalevel.at/prolog/clpfd

These are more recent resources that describe the latest developments, and&mdash;importantly&mdash;also link to the related academic publications.

Thank you!

**Comment by klauscfhq** [comment]
Thank you a lot for contributing : )
